parameters:


services:

  _defaults:
    autowire: true
    autoconfigure: true

  DeLoachTech\ZepherBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'
